version: '3.3'

services:
   nginx:
     build: ./nginx
     volumes:
       - public_data:/var/www/html
     restart: always
     ports:
      - "80:80"
     networks:
      - wordpress

   wordpress:
     depends_on:
       - db
     build: ./wordpress
     ports:
       - "9000:9000"
     restart: always
     volumes:
        - public_data:/var/www/html
     networks:
      - wordpress
   
volumes:
    public_data:

networks:
  wordpress:
    driver: bridge
